### ISSUE TITLE
Files are not ordered based on the created time

### ISSUE THREAD

**Issue by tiwanari** [wakate/wakate.github.io#14]
datetime に基づいた順になっているけど，どうやら作成日と違うみたい

**Comment by tiwanari** [comment]
日付だけだとダメですかね？
どの時間に合わせましょうか？

**Comment by tiwanari** [comment]
@izumin5210 これって各postファイルは命名規則ありますか？

**Comment by izumin5210** [comment]
middleman-blogというgem使ってるので，`{year}-{month}-{day}-{title}.html.md`のはずです！
もしかしたら生成するコマンドとかあったかもしれない

**Comment by tiwanari** [comment]
それに合わせて適当に変えても大丈夫？
2012年の記事は2012-みたいに

**Comment by izumin5210** [comment]
ファイル内のメタデータと不整合起きなければだいじょうぶ :ok_woman:

**Comment by tiwanari** [comment]
:+1:

**Comment by tiwanari** [comment]
# ファイルの本当の作成時間にファイル名を戻す

わからないやつは開催日の翌日にした

- 2011-07-25-20.html.md
    - OK
- 2011-09-02-21.html.md
    - OK
- 2012-03-26-4.html.md
    - 過去開催一覧 (これは別のページとしてほしい)
- 2012-03-26-5.html.md
    - 幹事一覧 (多分いらない？)
- 2012-03-26-6.html.md
    - 1996-09-03
- 2012-04-08-7.html.md
    - 2010-09-14
- 2012-04-08-8.html.md
    - 2009-09-22
- 2012-04-08-9.html.md
    - 2008-09-23
- 2012-04-08-10.html.md
    - 2007-09-18
- 2012-04-08-11.html.md
    - 2006-09-19
- 2012-04-08-12.html.md
    - 2005-09-13
- 2012-04-08-13.html.md
    - 2003-09-01
- 2012-04-08-14.html.md
    - 2002-09-03
- 2012-04-08-15.html.md
    - 2000-09-13
- 2012-04-08-16.html.md
    - 2001-09-16
- 2012-04-08-17.html.md
    - 1999-08-31
- 2012-04-08-18.html.md
    - 1998-09-06
- 2012-04-08-19.html.md
    - 1997-09-06
- 2012-06-18-22.html.md
    - 2011-09-20
- 2012-07-07-23.html.md
    - OK
- 2012-08-18-24.html.md
    - OK
- 2013-01-09-25.html.md
    - 2013-09-18
- 2013-06-30-26.html.md
    - OK
- 2013-07-12-27.html.md
    - OK
- 2013-09-20-28.html.md
    - OK
- 2014-01-11-29.html.md
    - OK
- 2014-01-12-30.html.md
    - OK (でもなくても良さそう)
- 2014-06-05-31.html.md
    - OK
- 2014-07-01-32.html.md
    - OK
- 2014-07-12-33.html.md
    - OK
- 2015-01-09-34.html.md
    - OK
- 2015-01-09-35.html.md
    - OK (でもなくても良さそう)
- 2015-05-17-36.html.md
    - OK
- 2015-06-03-37.html.md
    - OK
- 2015-10-06-38.html.md
    - 2004-09-06
- 2016-01-04-39.html.md
    - OK

**Comment by tiwanari** [comment]
名前変えたら #25 も変わる

**Comment by izumin5210** [comment]
さきにリネーム作業やったほうがいいかな？
チェックリストは`git ls-files source/posts/*.md | awk '{ print "- [ ] " $1 }'`で出せます :v:

**Comment by tiwanari** [comment]
寝ぼけてました…

**Comment by tiwanari** [comment]
個人的には綺麗に並んでから直したい！

**Comment by tiwanari** [comment]
今日 (2016/04/09) いずみんがやってくれる m(_ _)m

**Comment by daisuke-k** [comment]
ファイル名に title 入ってないと記事にならない様子？
