### ISSUE TITLE
Deploy with GitHub Actions

### ISSUE THREAD

**Issue by ishitatsuyuki** [wakate/wakate.github.io#185]
デプロイは現在手動になっているが、自動化したい。

Pages を Custom Actions Workflow からデプロイできる[機能](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow)が追加されているので、それを使うと良さそう (ただし beta であるという注意書きがある)。

ついでに、現在 Travis 経由で作っているリリースの zip も、Travis が有料化・過疎化していることを考慮して GHA に移すのが良さそう。

意見あればおしえてください。

cc @mt-caret

**Comment by musaprg** [comment]
PublicリポジトリなのでGHAの費用に関しても現状心配する必要はないですし、僕は全面的に賛成です

**Comment by ishitatsuyuki** [comment]
https://github.com/wakate/wakate.github.io/actions/runs/5911443414

できたと思います

**Comment by ishitatsuyuki** [comment]
プレビュー用に作っていたリリースの zip ですが、一旦廃止として、もし必要がありそうならプレビューの実装方法をいろいろ検討したいと思います
