### ISSUE TITLE
Check existing articles

### ISSUE THREAD

**Issue by izumin5210** [wakate/wakate.github.io#25]
fixed #15 #18

おかしな記事を探そう大会

- [ ] `source/posts/2011-07-25-20.html.md`
- [ ] `source/posts/2011-09-02-21.html.md`
- [ ] `source/posts/2012-03-26-4.html.md`
- [ ] `source/posts/2012-03-26-5.html.md`
- [ ] `source/posts/2012-03-26-6.html.md`
- [ ] `source/posts/2012-04-08-10.html.md`
- [ ] `source/posts/2012-04-08-11.html.md`
- [x] `source/posts/2012-04-08-12.html.md`
- [x] `source/posts/2012-04-08-13.html.md`
- [ ] `source/posts/2012-04-08-14.html.md`
- [ ] `source/posts/2012-04-08-15.html.md`
- [ ] `source/posts/2012-04-08-16.html.md`
- [ ] `source/posts/2012-04-08-17.html.md`
- [ ] `source/posts/2012-04-08-18.html.md`
- [x] `source/posts/2012-04-08-19.html.md`
- [x] `source/posts/2012-04-08-7.html.md`
- [x] `source/posts/2012-04-08-8.html.md`
- [x] `source/posts/2012-04-08-9.html.md`
- [ ] `source/posts/2012-06-18-22.html.md`
- [ ] `source/posts/2012-07-07-23.html.md`
- [ ] `source/posts/2012-08-18-24.html.md`
- [ ] `source/posts/2013-01-09-25.html.md`
- [ ] `source/posts/2013-06-30-26.html.md`
- [ ] `source/posts/2013-07-12-27.html.md`
- [ ] `source/posts/2013-09-20-28.html.md`
- [ ] `source/posts/2014-01-11-29.html.md`
- [ ] `source/posts/2014-01-12-30.html.md`
- [ ] `source/posts/2014-06-05-31.html.md`
- [ ] `source/posts/2014-07-01-32.html.md`
- [ ] `source/posts/2014-07-12-33.html.md`
- [ ] `source/posts/2015-01-09-34.html.md`
- [ ] `source/posts/2015-01-09-35.html.md`
- [ ] `source/posts/2015-05-17-36.html.md`
- [ ] `source/posts/2015-06-03-37.html.md`
- [ ] `source/posts/2015-10-06-38.html.md`
- [ ] `source/posts/2016-01-04-39.html.md`

**Comment by tiwanari** [comment]
ひとまず見たぞ！
修正が大きそうなやつだけチェックしたので他が大丈夫というわけではない…（みんなでチェック最終チェックしたい

**Comment by izumin5210** [comment]
問題あるやつ見つけたら適宜issue生やしていただければ潰します〜〜 :v:

**Comment by tiwanari** [comment]
さすがだった
