### ISSUE TITLE
Some pages may not be necessary

### ISSUE THREAD

**Issue by tiwanari** [wakate/wakate.github.io#36]
- 2012-03-26-4.html.md
    - 過去開催一覧 (これは別のページとしてほしい)
- 2012-03-26-5.html.md
    - 幹事一覧 (多分いらない？)
- 2014-01-12-30.html.md
    - 開催報告の公開通知 (開催報告は別記事．なくても良さそう)
- 2015-01-09-35.html.md
    - 開催報告の公開通知 (開催報告は別記事．なくても良さそう)

**Comment by izumin5210** [comment]
開催報告はtagつけてるから一覧見れます
動線はfooterにしかないですが… http://wakate.github.io/tags/%E9%96%8B%E5%82%AC%E5%A0%B1%E5%91%8A/

開催告知・募集記事は何もないですね

**Comment by tiwanari** [comment]
なるほど　tag があるのか
他のもタグがあると良いかも？
別の話だけど， By Year がちゃんと動いてない？？ 2012　とかがない

**Comment by daisuke-k** [comment]
確かに上の4ついらないです
