### ISSUE TITLE
Auto deploy is not working

### ISSUE THREAD

**Issue by daisuke-k** [wakate/wakate.github.io#38]
auto deploy されてなくね？

**Comment by izumin5210** [comment]
されてないです 😢 
原因究明中です〜

**Comment by tiwanari** [comment]
寝てました
これどういう状況です？

**Comment by daisuke-k** [comment]
deploy.sh が実行されるところまではデバッグしたけど、deploy のときに Ruby が 2.2 にならないバグが残ってる

**Comment by izumin5210** [comment]
ruby 1.9.3とかが使われてる…？

**Comment by asanon-s** [comment]
通りすがりですが、 .travis.yml の中に 下記が必要では？

```
language: ruby
rvm: 
    - 2.2.3
```
ref: http://jordanandree.com/travis-ci-deploy-middleman-github-pages/

**Comment by sowawa** [comment]
:+1:

**Comment by daisuke-k** [comment]
travis-ci のいろんな罠にはまりましたが無事動いた様子
