### ISSUE TITLE
kanji-core at wakate.org がなくなってる件

### ISSUE THREAD

**Issue by sowawa** [wakate/wakate.github.io#63]
幹事の皆さんにご連絡を取りたいのですが、
kanji-coreがなくなっていてメールが送れないので
可能であれば適当に幹事のメールアドレスをCCにいれて
私にメールしていただけませんか？

**Comment by daisuke-k** [comment]
info at wakate.org にご連絡ください

**Comment by sowawa** [comment]
:+1:
