### ISSUE TITLE
Change the DNS record(wakate.org) to wakate.github.io

### ISSUE THREAD

**Issue by sowawa** [wakate/wakate.github.io#7]
Please tell me when is the best time... :sleeping:

**Comment by daisuke-k** [comment]
This site is still under review by other members of the organization committee.

**Comment by sowawa** [comment]
:cherry_blossom:

**Comment by daisuke-k** [comment]
そわわさん、そろそろお願いします (このへん https://help.github.com/articles/setting-up-an-apex-domain/)

**Comment by sowawa** [comment]
✋

**Comment by sowawa** [comment]
@にcname貼れないから、www.wakate.orgに貼りました。そうするとwakate.github.ioにリダイレクトはられてて、wakate.orgに戻ってきてしまうようです。

**Comment by daisuke-k** [comment]
wakate.org の A レコードに
192.30.252.153
192.30.252.154
の2つを追加していただくだけでよいはずです

**Comment by sowawa** [comment]
すみません、下まで読んでなかった :bow:

**Comment by sowawa** [comment]
完了しました

**Comment by daisuke-k** [comment]
:+1:
